### ISSUE TITLE
Create SpaceGrid Logo

### ISSUE THREAD

**Issue by JonathanSpeek** [JonathanSpeek/spacegrid#5]
I'm looking for a new logo for SpaceGrid:
- SVG format
- Space theme
- Creative
- Have fun

**Comment by xeon-zolt** [comment]
hmm , what is space grid ? it can help making logo

**Comment by JonathanSpeek** [comment]
@xeon-zolt SpaceGrid is a responsive grid system to help developers get started on projects. It's a structure very similar to Bootstrap's columns that helps you align elements horizontally. See [here](http://getbootstrap.com/css/#grid-example-basic) for Bootstrap's version.
