### ISSUE TITLE
Example Landing Page

### ISSUE THREAD

**Issue by JonathanSpeek** [JonathanSpeek/spacegrid#8]
The more examples of SpaceGrid in action, the better. It would be great to have a simple landing page that uses SpaceGrid. 

Acceptance criteria:
- Simple and modern design
- Uses SpaceGrid, but can be highly customized

Go checkout [these](https://startbootstrap.com/template-categories/landing-pages/) for inspiration.

**Comment by techtolentino** [comment]
I'm down to make an example 😄
